### ISSUE TITLE
Why does the virtualFile Read method loop over back to the start?

### ISSUE THREAD

**Issue by hasen-mtic** [gobuffalo/packd#9]
I noticed the following snippet in `file.go`:

```go
// Read reads the next len(p) bytes from the virtualFile and
// rewind read offset to 0 when it met EOF.
func (f *virtualFile) Read(p []byte) (int, error) {
    i, err := f.Reader.Read(p)

    if i == 0 || err == io.EOF {
        f.Seek(0, io.SeekStart)
    }
    return i, err
}
```

It makes it so that when a file hits EOF, subsequent reads don't return EOF, instead return the bytes from the start of the file.

This is surprising behavior and violates the expectation of at least one package in the standard library: the csv package.

The documentation for `io.Reader` explicitly mentions that subsequent reads after an EOF is hit should return `(0, EOF)`

Source: https://golang.org/pkg/io/#Reader

Quote (emphasis mine)

> When Read encounters an error or end-of-file condition after successfully reading n > 0 bytes, it returns the number of bytes read. It may return the (non-nil) error from the same call or return the error (and n == 0) from a subsequent call. **An instance of this general case is that a Reader returning a non-zero number of bytes at the end of the input stream may return either err == EOF or err == nil. The next Read should return 0, EOF.**

> Callers should always process the n > 0 bytes returned before considering the error err. Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors.

The csv reader expects the Reader to return an EOF on the next read after it encounters an EOF, so if while reading a line it hits EOF instead of '\n', it doesn't do anything to handle the error there; it expects the next Read to return an EOF so it defers handling the error to the next read.

But the `*virtualFile` violates this assumption. Since the file rewinds back to position 0, the next csv read will read the first line again, thus preventing the csv reader from ever seeing the end of file.

What is the reason for rewinding back to start after hitting EOF? Would a PR to "correct" this be accepted?

**Comment by markbates** [comment]
Without that line the file can’t be re-read. As you can imagine this has caused numerous issues in the past forcing the code to be rewritten multiple times to squash the whack a mole bugs that pop up while trying to do this sort of thing.

**Comment by hasen-mtic** [comment]
Why does the file need to be re-read? That's what I don't understand. Under what circumstance do you want the same file instance to be read over and over again? I can't imagine a situation where that would be desirable; that's why I'm asking.

**Comment by markbates** [comment]
When the files are in memory and being asked for repeatedly. An example would be using a box of in memory files to serve a public directory over http. If it can be re read the file will be served one and then never served again.

**Comment by hasen-mtic** [comment]
Surely you can't use the same file instance to server multiple requests? What happens when you two concurrent request ask for the same file?

**Comment by markbates** [comment]
I didn’t say it was perfect. I just told you why a file might need to be re-read as you asked. PRs are welcome. If you’re proposing changes, especially those of a breaking nature, I would recommend opening a proposal ticket making it addresses the concerns of in memory files, both concurrently and in cases, like passing a file around in a generator.

**Comment by hasen-mtic** [comment]
I was hoping for more information on the use case that makes this needed so that I can make a PR that doesn't break the original use case.

**Comment by markbates** [comment]
The history of that piece of code goes back years over various libraries and is the result of a lot of issues from a lot of people around their use cases, much like this one. This is where the code has evolved too. I can’t tell you all of the reasons the file is re-readable, because I don’t know them all. I know one of the use cases I use it for it is when writing generators. I can pull a file out then read it as often as I need to as it gets passed around through transformers, ast parsers, formatters, templating systems, etc... the current expectation is the file can be reread. If that changes, it’s a breaking change. If you can come up with a fix for your use case, while not breaking everyone else who expects it to be re-readable  for whatever their use cases are, then awesome. If the goal is to change that, and break that expectation, then a deeper discussion needs to be had. I would love to tell it’s exact reason why it is, but there isn’t just one. There’s just a lot of history that got it here.

**Comment by hasen-mtic** [comment]
> I know one of the use cases I use it for it is when writing generators. I can pull a file out then read it as often as I need to as it gets passed around through transformers, ast parsers, formatters, templating systems, etc

If that system is part of packr or another open repository I would be happy to send a PR that covers it as well (if you could point me to it). If it's not, then I guess there's nothing I can do about it.

**Comment by markbates** [comment]
https://godoc.org/github.com/gobuffalo/packd?importers

I can’t judge who else is using it in their applications. This is a breaking change. It’s too widely used to alter its behavior without going to a new version.

**Comment by hasen-mtic** [comment]
ok, no problem.

For now I have a reasonable work around so I'm happy to continue using it the way it is. 

I like it (packr) a lot more than the other options I tried to look at.

```go
func CSVReaderFromBox(box packr.Box, filename string) *csv.Reader {
	var content, err = box.Find(filename)
	if err != nil {
		return nil
	}
	return csv.NewReader(bytes.NewReader(content))
}
```
